import jsPDF from 'jspdf';

export function exportToPDF(content) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 18;
  const contentW = pageW - margin * 2;
  let y = 20;

  const checkPage = (needed = 10) => {
    if (y + needed > 275) { doc.addPage(); y = 20; }
  };

  // Header
  doc.setFillColor(15, 31, 53);
  doc.rect(0, 0, pageW, 35, 'F');
  doc.setTextColor(249, 115, 22);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Exam Booster', margin, 14);
  doc.setFontSize(11);
  doc.setTextColor(200, 210, 220);
  doc.setFont('helvetica', 'normal');
  doc.text(`Topic: ${content.topic}`, margin, 22);
  doc.text(`Paper: ${content.gsPaper} | Theme: ${content.theme || 'General'}`, margin, 29);
  y = 44;

  const addSection = (title, textLines, color = [249, 115, 22]) => {
    checkPage(18);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...color);
    doc.text(title, margin, y);
    y += 6;
    doc.setDrawColor(...color);
    doc.setLineWidth(0.4);
    doc.line(margin, y, margin + contentW, y);
    y += 5;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(50, 60, 80);

    textLines.forEach((line) => {
      checkPage(7);
      const wrapped = doc.splitTextToSize(line, contentW);
      wrapped.forEach((wl) => {
        checkPage(6);
        doc.text(wl, margin, y);
        y += 5.5;
      });
      y += 1;
    });
    y += 4;
  };

  // Introduction
  addSection('INTRODUCTION', [content.introduction]);

  // Main Points
  if (content.body?.mainPoints?.length) {
    addSection('KEY ANALYSIS POINTS', content.body.mainPoints.map((p, i) => `${i + 1}. ${p}`));
  }

  // Conclusion
  addSection('CONCLUSION', [content.conclusion]);

  // India Case Studies
  if (content.indiaCaseStudies?.length) {
    addSection('INDIA CASE STUDIES', content.indiaCaseStudies.map(c =>
      `▸ ${c.title} (${c.location}, ${c.year})\n   ${c.description}\n   Impact: ${c.impact}`
    ), [34, 197, 94]);
  }

  // Global Case Studies
  if (content.globalCaseStudies?.length) {
    addSection('GLOBAL CASE STUDIES', content.globalCaseStudies.map(c =>
      `▸ ${c.title} (${c.location}, ${c.year})\n   ${c.description}`
    ), [59, 130, 246]);
  }

  // Quotes
  if (content.quotes?.length) {
    addSection('RELEVANT QUOTES', content.quotes.map(q =>
      `"${q.text}" — ${q.author} (${q.source})`
    ), [168, 85, 247]);
  }

  // Ethical Examples
  if (content.ethicalExamples?.length) {
    addSection('GS4 ETHICAL DIMENSIONS', content.ethicalExamples, [251, 146, 60]);
  }

  // Committees
  if (content.committees?.length) {
    addSection('COMMITTEES & REPORTS', content.committees, [20, 184, 166]);
  }

  // Government Schemes
  if (content.governmentSchemes?.length) {
    addSection('GOVERNMENT SCHEMES & ARTICLES', content.governmentSchemes, [99, 102, 241]);
  }

  // Footer
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by Exam Booster | Page ${i} of ${totalPages}`, margin, 290);
    doc.text(new Date().toLocaleDateString('en-IN'), pageW - margin, 290, { align: 'right' });
  }

  doc.save(`UPSC_${content.topic.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
}

export function exportToMarkdown(content) {
  let md = `# Exam: ${content.topic}\n\n`;
  md += `**Paper:** ${content.gsPaper} | **Theme:** ${content.theme || 'General'}\n\n`;
  md += `**Keywords:** ${(content.keywords || []).join(', ')}\n\n---\n\n`;

  md += `## Introduction\n${content.introduction}\n\n`;

  if (content.body?.mainPoints?.length) {
    md += `## Key Analysis Points\n`;
    content.body.mainPoints.forEach((p, i) => { md += `${i + 1}. ${p}\n`; });
    md += '\n';
  }

  if (content.body?.analysis) md += `## Critical Analysis\n${content.body.analysis}\n\n`;

  md += `## Conclusion\n${content.conclusion}\n\n`;

  if (content.indiaCaseStudies?.length) {
    md += `## India Case Studies\n`;
    content.indiaCaseStudies.forEach(c => {
      md += `### ${c.title} (${c.location}, ${c.year})\n${c.description}\n**Relevance:** ${c.relevance}\n**Impact:** ${c.impact}\n\n`;
    });
  }

  if (content.globalCaseStudies?.length) {
    md += `## Global Case Studies\n`;
    content.globalCaseStudies.forEach(c => {
      md += `### ${c.title} (${c.location}, ${c.year})\n${c.description}\n**Lessons for India:** ${c.relevance}\n\n`;
    });
  }

  if (content.quotes?.length) {
    md += `## Relevant Quotes\n`;
    content.quotes.forEach(q => { md += `> "${q.text}"\n> — **${q.author}** *(${q.source})*\n\n`; });
  }

  if (content.ethicalExamples?.length) {
    md += `## GS4 Ethical Dimensions\n`;
    content.ethicalExamples.forEach(e => { md += `- ${e}\n`; });
    md += '\n';
  }

  if (content.committees?.length) {
    md += `## Committees & Reports\n`;
    content.committees.forEach(c => { md += `- ${c}\n`; });
    md += '\n';
  }

  if (content.governmentSchemes?.length) {
    md += `## Government Schemes & Articles\n`;
    content.governmentSchemes.forEach(s => { md += `- ${s}\n`; });
    md += '\n';
  }

  md += `---\n*Generated by Exam Booster on ${new Date().toLocaleDateString('en-IN')}*\n`;

  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `UPSC_${content.topic.replace(/\s+/g, '_')}.md`;
  a.click();
  URL.revokeObjectURL(url);
}
